In [2]:
import pandas as pd

In [80]:
df_assemblies_01 = pd.read_csv('assemblies_0111-1511.csv', sep=',')
df_assemblies_01

,assembly_id,box_id,store_format,sku,amount
0,0000b6a4-445c-4f9e-b5d8-97b75332755f,5b4e7a6f-ec88-40a0-96ea-d9118c0fda34,МД/Супермаркет,10,11
1,000140d8-42e0-44f7-9f47-2460c52e241c,148da139-db62-4379-92af-2ed792723d45,МД/Магазин у дома,14,14
2,00019029-70e1-46e6-a454-b9c0c2158ee9,b1563abd-991d-46e0-8f96-affb6a2272f5,МД/Супермаркет,23,26
3,00023603-c39b-4db6-a4a0-356ff1613504,f830b34e-8cec-4207-a377-4154f60ebf63,МК/Мегаполис МК,12,12
4,00026957-a6d2-4fcb-aac8-716c368d84b4,018a67b7-7e3f-47d7-8ae9-1d9a81672c6c,МД/Магазин у дома,10,10
...,...,...,...,...,...
249642,fffe6482-8aa6-4acf-9302-2554d56122a2,4ddf58b6-4bed-43b1-b902-9ea634e147cf,МД/Магазин у дома,24,52
249643,fffe764f-0879-41c9-bd45-c951abc1e54f,f6d41808-6e5b-4340-be01-b91ed02862a2,МД/Магазин у дома,15,41
249644,fffe96a1-553c-4d27-aa32-68951f60ed95,28f0b261-f209-48b2-87b7-5ea30f48e273,МК/Город МК,13,19
249645,ffffccd0-1cf6-4461-a69b-cd567652c63b,f66fec28-ba31-4d46-b405-23f5394ec890,МД/Магазин у дома,10,14
249646,fffff9c3-bd9a-41df-be12-8fda6a2bff1d,af2560b9-006d-4d55-9d41-e2f430c30506,МД/Мини-Даркстор,10,11

In [81]:
df_histories_01 = pd.read_csv('histories_0111-1511.csv', sep=',')
df_histories_01

,id,assembly_id,status,created_at,collector_code
0,6cb9b171-6bce-46c9-91bf-6a824b4b3940,64d84254-728d-4831-93ca-6aec01a6ffe4,assembly,2022-11-01 06:33:19.667219+03,74950005992
1,f5632824-d389-43cf-a6bc-7c654e9f9893,4250b381-a934-43ac-9a15-f6ce493502fe,assembly,2022-11-01 05:08:52.432497+03,sb543387001
2,88cb34bc-b282-48eb-9013-6b376240f872,691695b9-c9a9-4dcb-b303-e40253f51a77,assembly,2022-11-01 05:17:20.625372+03,74950005651
3,b9e15d13-2188-45f6-a2a2-20fcb965f655,40cbd128-d1fa-430b-b3fa-91a60f2dff27,assembly,2022-11-01 05:18:46.654925+03,74950010125
4,f317273a-d84e-44cd-a9e3-6a0c28c8e79f,691695b9-c9a9-4dcb-b303-e40253f51a77,assembled,2022-11-01 05:43:28.993577+03,74950005651
...,...,...,...,...,...
485858,dd799e59-5330-47ce-a530-e30c6dbf35c5,ce55a535-9b40-4780-8c9d-6c3a1b16e3e7,assembled,2022-11-15 22:54:24.674426+03,74950004573
485859,92c2f0bb-d2e5-41b1-9247-b82d28f17b04,85ee7b5b-3ef2-431c-9108-79ce38eada10,assembled,2022-11-15 22:56:33.297008+03,74950008554
485860,52a065e5-f953-4705-bce7-3cf168975da1,df5da842-eca8-497f-8826-40b307a4927e,assembly,2022-11-15 22:56:56.599632+03,74950006397
485861,46ffad42-ba1e-459e-8a70-f899fe085302,907d66cd-3603-4e70-bae2-c9f4333df75d,assembly,2022-11-15 22:58:41.242683+03,74950002265
485862,c6378057-80b6-4a7c-a0ac-184c8708929b,4fdd6210-956c-4f74-a289-a50bff126e43,assembled,2022-11-15 23:38:05.432493+03,995667

In [82]:
df_histories_01['assembly_datetime'] = [
    df_histories_01['created_at'][i] if df_histories_01['status'][i] == 'assembly' else 0
    for i in range(len(df_histories_01)) 
]
df_histories_01

,id,assembly_id,status,created_at,collector_code,assembly_datetime
0,6cb9b171-6bce-46c9-91bf-6a824b4b3940,64d84254-728d-4831-93ca-6aec01a6ffe4,assembly,2022-11-01 06:33:19.667219+03,74950005992,2022-11-01 06:33:19.667219+03
1,f5632824-d389-43cf-a6bc-7c654e9f9893,4250b381-a934-43ac-9a15-f6ce493502fe,assembly,2022-11-01 05:08:52.432497+03,sb543387001,2022-11-01 05:08:52.432497+03
2,88cb34bc-b282-48eb-9013-6b376240f872,691695b9-c9a9-4dcb-b303-e40253f51a77,assembly,2022-11-01 05:17:20.625372+03,74950005651,2022-11-01 05:17:20.625372+03
3,b9e15d13-2188-45f6-a2a2-20fcb965f655,40cbd128-d1fa-430b-b3fa-91a60f2dff27,assembly,2022-11-01 05:18:46.654925+03,74950010125,2022-11-01 05:18:46.654925+03
4,f317273a-d84e-44cd-a9e3-6a0c28c8e79f,691695b9-c9a9-4dcb-b303-e40253f51a77,assembled,2022-11-01 05:43:28.993577+03,74950005651,0
...,...,...,...,...,...,...
485858,dd799e59-5330-47ce-a530-e30c6dbf35c5,ce55a535-9b40-4780-8c9d-6c3a1b16e3e7,assembled,2022-11-15 22:54:24.674426+03,74950004573,0
485859,92c2f0bb-d2e5-41b1-9247-b82d28f17b04,85ee7b5b-3ef2-431c-9108-79ce38eada10,assembled,2022-11-15 22:56:33.297008+03,74950008554,0
485860,52a065e5-f953-4705-bce7-3cf168975da1,df5da842-eca8-497f-8826-40b307a4927e,assembly,2022-11-15 22:56:56.599632+03,74950006397,2022-11-15 22:56:56.599632+03
485861,46ffad42-ba1e-459e-8a70-f899fe085302,907d66cd-3603-4e70-bae2-c9f4333df75d,assembly,2022-11-15 22:58:41.242683+03,74950002265,2022-11-15 22:58:41.242683+03
485862,c6378057-80b6-4a7c-a0ac-184c8708929b,4fdd6210-956c-4f74-a289-a50bff126e43,assembled,2022-11-15 23:38:05.432493+03,995667,0

In [83]:
df_histories_01['assembled_datetime'] = [
    df_histories_01['created_at'][i] if df_histories_01['status'][i] == 'assembled' else 0
    for i in range(len(df_histories_01)) 
]
df_histories_01

,id,assembly_id,status,created_at,collector_code,assembly_datetime,assembled_datetime
0,6cb9b171-6bce-46c9-91bf-6a824b4b3940,64d84254-728d-4831-93ca-6aec01a6ffe4,assembly,2022-11-01 06:33:19.667219+03,74950005992,2022-11-01 06:33:19.667219+03,0
1,f5632824-d389-43cf-a6bc-7c654e9f9893,4250b381-a934-43ac-9a15-f6ce493502fe,assembly,2022-11-01 05:08:52.432497+03,sb543387001,2022-11-01 05:08:52.432497+03,0
2,88cb34bc-b282-48eb-9013-6b376240f872,691695b9-c9a9-4dcb-b303-e40253f51a77,assembly,2022-11-01 05:17:20.625372+03,74950005651,2022-11-01 05:17:20.625372+03,0
3,b9e15d13-2188-45f6-a2a2-20fcb965f655,40cbd128-d1fa-430b-b3fa-91a60f2dff27,assembly,2022-11-01 05:18:46.654925+03,74950010125,2022-11-01 05:18:46.654925+03,0
4,f317273a-d84e-44cd-a9e3-6a0c28c8e79f,691695b9-c9a9-4dcb-b303-e40253f51a77,assembled,2022-11-01 05:43:28.993577+03,74950005651,0,2022-11-01 05:43:28.993577+03
...,...,...,...,...,...,...,...
485858,dd799e59-5330-47ce-a530-e30c6dbf35c5,ce55a535-9b40-4780-8c9d-6c3a1b16e3e7,assembled,2022-11-15 22:54:24.674426+03,74950004573,0,2022-11-15 22:54:24.674426+03
485859,92c2f0bb-d2e5-41b1-9247-b82d28f17b04,85ee7b5b-3ef2-431c-9108-79ce38eada10,assembled,2022-11-15 22:56:33.297008+03,74950008554,0,2022-11-15 22:56:33.297008+03
485860,52a065e5-f953-4705-bce7-3cf168975da1,df5da842-eca8-497f-8826-40b307a4927e,assembly,2022-11-15 22:56:56.599632+03,74950006397,2022-11-15 22:56:56.599632+03,0
485861,46ffad42-ba1e-459e-8a70-f899fe085302,907d66cd-3603-4e70-bae2-c9f4333df75d,assembly,2022-11-15 22:58:41.242683+03,74950002265,2022-11-15 22:58:41.242683+03,0
485862,c6378057-80b6-4a7c-a0ac-184c8708929b,4fdd6210-956c-4f74-a289-a50bff126e43,assembled,2022-11-15 23:38:05.432493+03,995667,0,2022-11-15 23:38:05.432493+03

In [84]:
df_hist_assembly_01 = df_histories_01[df_histories_01['assembly_datetime'] != 0]
assembly_cols = df_hist_assembly_01.columns.to_list()
assembly_cols.pop(1)
assembly_cols.pop(-2)
df_hist_assembly_01.drop(assembly_cols, axis=1, inplace=True)
df_hist_assembly_01

/var/folders/zx/nj1m60_x22vbybt3fxz1nzkc0000gn/T/ipykernel_6282/2518499311.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hist_assembly_01.drop(assembly_cols, axis=1, inplace=True)

                                 assembly_id              assembly_datetime
0       64d84254-728d-4831-93ca-6aec01a6ffe4  2022-11-01 06:33:19.667219+03
1       4250b381-a934-43ac-9a15-f6ce493502fe  2022-11-01 05:08:52.432497+03
2       691695b9-c9a9-4dcb-b303-e40253f51a77  2022-11-01 05:17:20.625372+03
3       40cbd128-d1fa-430b-b3fa-91a60f2dff27  2022-11-01 05:18:46.654925+03
6       6cf8dda2-7407-48bf-905e-8e1f838946e5  2022-11-01 05:46:17.401079+03
...                                      ...                            ...
485847  97bc1939-f8ec-4391-8e17-5e705167f85f   2022-11-15 22:48:21.81212+03
485848  84807769-7cd1-430b-bcad-c5be874e5b77  2022-11-15 22:26:01.080369+03
485849  1309f9b5-4b83-447f-8b97-1dc0d68ab788   2022-11-15 22:27:09.25115+03
485860  df5da842-eca8-497f-8826-40b307a4927e  2022-11-15 22:56:56.599632+03
485861  907d66cd-3603-4e70-bae2-c9f4333df75d  2022-11-15 22:58:41.242683+03

[243869 rows x 2 columns]

In [85]:
df_hist_assembled_01 = df_histories_01[df_histories_01['assembled_datetime'] != 0]
assembled_cols = df_hist_assembled_01.columns.to_list()
assembled_cols.pop(1)
assembled_cols.pop(-1)
df_hist_assembled_01.drop(assembled_cols, axis=1, inplace=True)
df_hist_assembled_01

/var/folders/zx/nj1m60_x22vbybt3fxz1nzkc0000gn/T/ipykernel_6282/1206566704.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hist_assembled_01.drop(assembled_cols, axis=1, inplace=True)

                                 assembly_id             assembled_datetime
4       691695b9-c9a9-4dcb-b303-e40253f51a77  2022-11-01 05:43:28.993577+03
5       4250b381-a934-43ac-9a15-f6ce493502fe  2022-11-01 05:45:00.506399+03
7       40cbd128-d1fa-430b-b3fa-91a60f2dff27  2022-11-01 05:54:53.208319+03
12      f596031e-c5b9-40e9-945a-9214f00b3a66   2022-11-01 06:09:49.43535+03
14      aaca8068-c0ff-4198-b080-ad6f086e615c  2022-11-01 06:11:28.165737+03
...                                      ...                            ...
485856  df5da842-eca8-497f-8826-40b307a4927e  2022-11-15 23:10:06.124141+03
485857  97bc1939-f8ec-4391-8e17-5e705167f85f  2022-11-15 22:52:34.540506+03
485858  ce55a535-9b40-4780-8c9d-6c3a1b16e3e7  2022-11-15 22:54:24.674426+03
485859  85ee7b5b-3ef2-431c-9108-79ce38eada10  2022-11-15 22:56:33.297008+03
485862  4fdd6210-956c-4f74-a289-a50bff126e43  2022-11-15 23:38:05.432493+03

[241994 rows x 2 columns]

In [86]:
df_histories_01 = pd.merge(df_hist_assembly_01, df_hist_assembled_01, how='inner', on='assembly_id')
df_01 = pd.merge(df_assemblies_01, df_histories_01, how='inner', on='assembly_id')
df_01

,assembly_id,box_id,store_format,sku,amount,assembly_datetime,assembled_datetime
0,0000b6a4-445c-4f9e-b5d8-97b75332755f,5b4e7a6f-ec88-40a0-96ea-d9118c0fda34,МД/Супермаркет,10,11,2022-11-06 10:46:41.224447+03,2022-11-06 10:51:02.074923+03
1,000140d8-42e0-44f7-9f47-2460c52e241c,148da139-db62-4379-92af-2ed792723d45,МД/Магазин у дома,14,14,2022-11-12 19:06:37.021463+03,2022-11-12 19:15:34.670312+03
2,00019029-70e1-46e6-a454-b9c0c2158ee9,b1563abd-991d-46e0-8f96-affb6a2272f5,МД/Супермаркет,23,26,2022-11-01 13:49:13.915697+03,2022-11-01 14:08:32.053658+03
3,00023603-c39b-4db6-a4a0-356ff1613504,f830b34e-8cec-4207-a377-4154f60ebf63,МК/Мегаполис МК,12,12,2022-11-08 19:00:18.071688+03,2022-11-08 19:10:58.455788+03
4,00026957-a6d2-4fcb-aac8-716c368d84b4,018a67b7-7e3f-47d7-8ae9-1d9a81672c6c,МД/Магазин у дома,10,10,2022-11-09 11:28:10.573588+03,2022-11-09 11:36:46.808569+03
...,...,...,...,...,...,...,...
242080,fffe6482-8aa6-4acf-9302-2554d56122a2,4ddf58b6-4bed-43b1-b902-9ea634e147cf,МД/Магазин у дома,24,52,2022-11-01 15:33:16.543513+03,2022-11-01 15:51:14.898933+03
242081,fffe764f-0879-41c9-bd45-c951abc1e54f,f6d41808-6e5b-4340-be01-b91ed02862a2,МД/Магазин у дома,15,41,2022-11-11 10:31:03.169924+03,2022-11-11 10:49:08.613723+03
242082,fffe96a1-553c-4d27-aa32-68951f60ed95,28f0b261-f209-48b2-87b7-5ea30f48e273,МК/Город МК,13,19,2022-11-12 12:10:22.86709+03,2022-11-12 12:23:14.170655+03
242083,ffffccd0-1cf6-4461-a69b-cd567652c63b,f66fec28-ba31-4d46-b405-23f5394ec890,МД/Магазин у дома,10,14,2022-11-12 18:01:05.556108+03,2022-11-12 18:10:22.826229+03
242084,fffff9c3-bd9a-41df-be12-8fda6a2bff1d,af2560b9-006d-4d55-9d41-e2f430c30506,МД/Мини-Даркстор,10,11,2022-11-04 12:59:18.11166+03,2022-11-04 13:05:20.68186+03

In [87]:
df_01.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 242085 entries, 0 to 242084
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   assembly_id         242085 non-null  object
 1   box_id              242085 non-null  object
 2   store_format        242085 non-null  object
 3   sku                 242085 non-null  int64
 4   amount              242085 non-null  int64
 5   assembly_datetime   242085 non-null  object
 6   assembled_datetime  242085 non-null  object
dtypes: int64(2), object(5)
memory usage: 14.8+ MB

In [88]:
df_assemblies_02 = pd.read_csv('assemblies_1611-3011.csv', sep=',')
df_assemblies_02

,assembly_id,box_id,store_format,sku,amount
0,00002af3-2ac9-41fe-a309-726821d4a9c8,a59ef342-542a-4eef-a77c-f6c9c4084205,МД/Магазин у дома,2,6
1,0000a3c6-59af-4d95-a5f8-4af5748c8d78,0914776e-a6dd-4fd6-84b9-6278af73d632,БФ/L+,21,29
2,0000fbef-99f6-42cd-a0a7-48eeca32c020,106ff7fe-a5cf-4dbc-82ae-256ced71e824,МД/Супермаркет,19,25
3,00011784-5d9e-4619-a0f1-e4571172fe99,9cbbb036-1a79-4ef2-b496-91317c1645a3,МД/Супермаркет,11,46
4,000199ea-aa2e-4285-baa8-efbae1e44f46,a45811f5-99f0-40f1-8fc8-108fcc508dfc,МД/Супермаркет,13,18
...,...,...,...,...,...
236676,ffff1987-da1a-462e-8161-a6a8928def60,7bae2653-ad9d-49ac-a2e4-0d912f075597,МД/Супермаркет,17,24
236677,ffff365d-e8a5-44a6-81b4-6a23edec17de,cae08e0b-17d1-4163-bf12-897c81790fd0,МД/Мини-Даркстор,48,59
236678,ffff77de-8838-4f6d-854b-1fb868f409d1,136dcb3b-f893-4d85-8f5b-1d780156cbe2,МД/Магазин у дома,4,4
236679,ffffb5a2-18dc-4b7c-aaea-614f2164603d,4978744f-5fea-4e50-98e2-dfea919924ed,МД/Магазин у дома,16,21
236680,ffffd931-0fc6-453b-8b31-5dd95cf353f5,75ca1b09-c22a-435c-acfa-d83231485586,МД/Мини-Даркстор,10,16

In [89]:
df_histories_02 = pd.read_csv('histories_1611-3011.csv', sep=',')
df_histories_02

,id,assembly_id,status,created_at,collector_code
0,295f6844-ec80-4c9b-9afb-23570c425f8b,00002af3-2ac9-41fe-a309-726821d4a9c8,assembled,2022-11-29 13:27:13.119795+03,TNSZ-00667
1,2706616c-fa3f-4726-b324-e659318a3227,00002af3-2ac9-41fe-a309-726821d4a9c8,assembly,2022-11-29 13:24:19.733199+03,TNSZ-00667
2,096f8d7e-3357-4178-a9c5-9d2be76c1ce6,0000a3c6-59af-4d95-a5f8-4af5748c8d78,assembled,2022-11-19 14:41:31.840732+03,74950008587
3,6ebd417a-0481-488a-8646-5aa0b9decd11,0000a3c6-59af-4d95-a5f8-4af5748c8d78,assembly,2022-11-19 14:27:50.866042+03,74950008587
4,d14dabb3-6d4d-4c56-a114-7e343a7ae945,0000fbef-99f6-42cd-a0a7-48eeca32c020,assembled,2022-11-26 18:22:00.46523+03,79022823002
...,...,...,...,...,...
463277,8e6f1197-d543-473b-95e8-7ab15cad25ce,ffff77de-8838-4f6d-854b-1fb868f409d1,assembly,2022-11-22 14:57:27.776063+03,74950009975
463278,a7106fd1-a51a-49a3-b300-f85c3b1109b9,ffffb5a2-18dc-4b7c-aaea-614f2164603d,assembled,2022-11-16 11:17:57.616853+03,sb340072005
463279,ddf4a414-43f3-4e80-b921-9074076dcdfc,ffffb5a2-18dc-4b7c-aaea-614f2164603d,assembly,2022-11-16 10:59:02.245041+03,sb340072005
463280,da7fb075-4eac-4d18-95d3-a91c3c2c8749,ffffd931-0fc6-453b-8b31-5dd95cf353f5,assembled,2022-11-22 13:49:41.69869+03,74950004579
463281,7f4f41e8-9683-4e56-a362-e8186af79e81,ffffd931-0fc6-453b-8b31-5dd95cf353f5,assembly,2022-11-22 13:35:31.347859+03,74950004579

In [90]:
df_histories_02['assembly_datetime'] = [
    df_histories_02['created_at'][i] if df_histories_02['status'][i] == 'assembly' else 0
    for i in range(len(df_histories_02)) 
]
df_histories_02

,id,assembly_id,status,created_at,collector_code,assembly_datetime
0,295f6844-ec80-4c9b-9afb-23570c425f8b,00002af3-2ac9-41fe-a309-726821d4a9c8,assembled,2022-11-29 13:27:13.119795+03,TNSZ-00667,0
1,2706616c-fa3f-4726-b324-e659318a3227,00002af3-2ac9-41fe-a309-726821d4a9c8,assembly,2022-11-29 13:24:19.733199+03,TNSZ-00667,2022-11-29 13:24:19.733199+03
2,096f8d7e-3357-4178-a9c5-9d2be76c1ce6,0000a3c6-59af-4d95-a5f8-4af5748c8d78,assembled,2022-11-19 14:41:31.840732+03,74950008587,0
3,6ebd417a-0481-488a-8646-5aa0b9decd11,0000a3c6-59af-4d95-a5f8-4af5748c8d78,assembly,2022-11-19 14:27:50.866042+03,74950008587,2022-11-19 14:27:50.866042+03
4,d14dabb3-6d4d-4c56-a114-7e343a7ae945,0000fbef-99f6-42cd-a0a7-48eeca32c020,assembled,2022-11-26 18:22:00.46523+03,79022823002,0
...,...,...,...,...,...,...
463277,8e6f1197-d543-473b-95e8-7ab15cad25ce,ffff77de-8838-4f6d-854b-1fb868f409d1,assembly,2022-11-22 14:57:27.776063+03,74950009975,2022-11-22 14:57:27.776063+03
463278,a7106fd1-a51a-49a3-b300-f85c3b1109b9,ffffb5a2-18dc-4b7c-aaea-614f2164603d,assembled,2022-11-16 11:17:57.616853+03,sb340072005,0
463279,ddf4a414-43f3-4e80-b921-9074076dcdfc,ffffb5a2-18dc-4b7c-aaea-614f2164603d,assembly,2022-11-16 10:59:02.245041+03,sb340072005,2022-11-16 10:59:02.245041+03
463280,da7fb075-4eac-4d18-95d3-a91c3c2c8749,ffffd931-0fc6-453b-8b31-5dd95cf353f5,assembled,2022-11-22 13:49:41.69869+03,74950004579,0
463281,7f4f41e8-9683-4e56-a362-e8186af79e81,ffffd931-0fc6-453b-8b31-5dd95cf353f5,assembly,2022-11-22 13:35:31.347859+03,74950004579,2022-11-22 13:35:31.347859+03

In [91]:
df_histories_02['assembled_datetime'] = [
    df_histories_02['created_at'][i] if df_histories_02['status'][i] == 'assembled' else 0
    for i in range(len(df_histories_02)) 
]
df_histories_02

,id,assembly_id,status,created_at,collector_code,assembly_datetime,assembled_datetime
0,295f6844-ec80-4c9b-9afb-23570c425f8b,00002af3-2ac9-41fe-a309-726821d4a9c8,assembled,2022-11-29 13:27:13.119795+03,TNSZ-00667,0,2022-11-29 13:27:13.119795+03
1,2706616c-fa3f-4726-b324-e659318a3227,00002af3-2ac9-41fe-a309-726821d4a9c8,assembly,2022-11-29 13:24:19.733199+03,TNSZ-00667,2022-11-29 13:24:19.733199+03,0
2,096f8d7e-3357-4178-a9c5-9d2be76c1ce6,0000a3c6-59af-4d95-a5f8-4af5748c8d78,assembled,2022-11-19 14:41:31.840732+03,74950008587,0,2022-11-19 14:41:31.840732+03
3,6ebd417a-0481-488a-8646-5aa0b9decd11,0000a3c6-59af-4d95-a5f8-4af5748c8d78,assembly,2022-11-19 14:27:50.866042+03,74950008587,2022-11-19 14:27:50.866042+03,0
4,d14dabb3-6d4d-4c56-a114-7e343a7ae945,0000fbef-99f6-42cd-a0a7-48eeca32c020,assembled,2022-11-26 18:22:00.46523+03,79022823002,0,2022-11-26 18:22:00.46523+03
...,...,...,...,...,...,...,...
463277,8e6f1197-d543-473b-95e8-7ab15cad25ce,ffff77de-8838-4f6d-854b-1fb868f409d1,assembly,2022-11-22 14:57:27.776063+03,74950009975,2022-11-22 14:57:27.776063+03,0
463278,a7106fd1-a51a-49a3-b300-f85c3b1109b9,ffffb5a2-18dc-4b7c-aaea-614f2164603d,assembled,2022-11-16 11:17:57.616853+03,sb340072005,0,2022-11-16 11:17:57.616853+03
463279,ddf4a414-43f3-4e80-b921-9074076dcdfc,ffffb5a2-18dc-4b7c-aaea-614f2164603d,assembly,2022-11-16 10:59:02.245041+03,sb340072005,2022-11-16 10:59:02.245041+03,0
463280,da7fb075-4eac-4d18-95d3-a91c3c2c8749,ffffd931-0fc6-453b-8b31-5dd95cf353f5,assembled,2022-11-22 13:49:41.69869+03,74950004579,0,2022-11-22 13:49:41.69869+03
463281,7f4f41e8-9683-4e56-a362-e8186af79e81,ffffd931-0fc6-453b-8b31-5dd95cf353f5,assembly,2022-11-22 13:35:31.347859+03,74950004579,2022-11-22 13:35:31.347859+03,0

In [92]:
df_hist_assembly_02 = df_histories_02[df_histories_02['assembly_datetime'] != 0]
assembly_cols = df_hist_assembly_02.columns.to_list()
assembly_cols.pop(1)
assembly_cols.pop(-2)
df_hist_assembly_02.drop(assembly_cols, axis=1, inplace=True)
df_hist_assembly_02

/var/folders/zx/nj1m60_x22vbybt3fxz1nzkc0000gn/T/ipykernel_6282/2499117578.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hist_assembly_02.drop(assembly_cols, axis=1, inplace=True)

                                 assembly_id              assembly_datetime
1       00002af3-2ac9-41fe-a309-726821d4a9c8  2022-11-29 13:24:19.733199+03
3       0000a3c6-59af-4d95-a5f8-4af5748c8d78  2022-11-19 14:27:50.866042+03
5       0000fbef-99f6-42cd-a0a7-48eeca32c020  2022-11-26 18:01:40.186831+03
6       00011784-5d9e-4619-a0f1-e4571172fe99   2022-11-19 14:27:51.47076+03
8       000199ea-aa2e-4285-baa8-efbae1e44f46  2022-11-26 17:14:29.590708+03
...                                      ...                            ...
463272  ffff1987-da1a-462e-8161-a6a8928def60  2022-11-26 15:02:59.043008+03
463275  ffff365d-e8a5-44a6-81b4-6a23edec17de  2022-11-24 15:59:27.837839+03
463277  ffff77de-8838-4f6d-854b-1fb868f409d1  2022-11-22 14:57:27.776063+03
463279  ffffb5a2-18dc-4b7c-aaea-614f2164603d  2022-11-16 10:59:02.245041+03
463281  ffffd931-0fc6-453b-8b31-5dd95cf353f5  2022-11-22 13:35:31.347859+03

[232463 rows x 2 columns]

In [93]:
df_hist_assembled_02 = df_histories_02[df_histories_02['assembled_datetime'] != 0]
assembled_cols = df_hist_assembled_02.columns.to_list()
assembled_cols.pop(1)
assembled_cols.pop(-1)
df_hist_assembled_02.drop(assembled_cols, axis=1, inplace=True)
df_hist_assembled_02

/var/folders/zx/nj1m60_x22vbybt3fxz1nzkc0000gn/T/ipykernel_6282/815524335.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hist_assembled_02.drop(assembled_cols, axis=1, inplace=True)

                                 assembly_id             assembled_datetime
0       00002af3-2ac9-41fe-a309-726821d4a9c8  2022-11-29 13:27:13.119795+03
2       0000a3c6-59af-4d95-a5f8-4af5748c8d78  2022-11-19 14:41:31.840732+03
4       0000fbef-99f6-42cd-a0a7-48eeca32c020   2022-11-26 18:22:00.46523+03
7       00011784-5d9e-4619-a0f1-e4571172fe99   2022-11-19 14:49:16.16835+03
9       000199ea-aa2e-4285-baa8-efbae1e44f46  2022-11-26 17:23:42.160151+03
...                                      ...                            ...
463273  ffff1987-da1a-462e-8161-a6a8928def60  2022-11-26 15:52:23.129005+03
463274  ffff365d-e8a5-44a6-81b4-6a23edec17de   2022-11-24 16:31:18.20236+03
463276  ffff77de-8838-4f6d-854b-1fb868f409d1   2022-11-22 15:01:18.44135+03
463278  ffffb5a2-18dc-4b7c-aaea-614f2164603d  2022-11-16 11:17:57.616853+03
463280  ffffd931-0fc6-453b-8b31-5dd95cf353f5   2022-11-22 13:49:41.69869+03

[230819 rows x 2 columns]

In [94]:
df_histories_02 = pd.merge(df_hist_assembly_02, df_hist_assembled_02, how='inner', on='assembly_id')
df_02 = pd.merge(df_assemblies_02, df_histories_02, how='inner', on='assembly_id')
df_02

,assembly_id,box_id,store_format,sku,amount,assembly_datetime,assembled_datetime
0,00002af3-2ac9-41fe-a309-726821d4a9c8,a59ef342-542a-4eef-a77c-f6c9c4084205,МД/Магазин у дома,2,6,2022-11-29 13:24:19.733199+03,2022-11-29 13:27:13.119795+03
1,0000a3c6-59af-4d95-a5f8-4af5748c8d78,0914776e-a6dd-4fd6-84b9-6278af73d632,БФ/L+,21,29,2022-11-19 14:27:50.866042+03,2022-11-19 14:41:31.840732+03
2,0000fbef-99f6-42cd-a0a7-48eeca32c020,106ff7fe-a5cf-4dbc-82ae-256ced71e824,МД/Супермаркет,19,25,2022-11-26 18:01:40.186831+03,2022-11-26 18:22:00.46523+03
3,00011784-5d9e-4619-a0f1-e4571172fe99,9cbbb036-1a79-4ef2-b496-91317c1645a3,МД/Супермаркет,11,46,2022-11-19 14:27:51.47076+03,2022-11-19 14:49:16.16835+03
4,000199ea-aa2e-4285-baa8-efbae1e44f46,a45811f5-99f0-40f1-8fc8-108fcc508dfc,МД/Супермаркет,13,18,2022-11-26 17:14:29.590708+03,2022-11-26 17:23:42.160151+03
...,...,...,...,...,...,...,...
230913,ffff1987-da1a-462e-8161-a6a8928def60,7bae2653-ad9d-49ac-a2e4-0d912f075597,МД/Супермаркет,17,24,2022-11-26 15:02:59.043008+03,2022-11-26 15:52:23.129005+03
230914,ffff365d-e8a5-44a6-81b4-6a23edec17de,cae08e0b-17d1-4163-bf12-897c81790fd0,МД/Мини-Даркстор,48,59,2022-11-24 15:59:27.837839+03,2022-11-24 16:31:18.20236+03
230915,ffff77de-8838-4f6d-854b-1fb868f409d1,136dcb3b-f893-4d85-8f5b-1d780156cbe2,МД/Магазин у дома,4,4,2022-11-22 14:57:27.776063+03,2022-11-22 15:01:18.44135+03
230916,ffffb5a2-18dc-4b7c-aaea-614f2164603d,4978744f-5fea-4e50-98e2-dfea919924ed,МД/Магазин у дома,16,21,2022-11-16 10:59:02.245041+03,2022-11-16 11:17:57.616853+03
230917,ffffd931-0fc6-453b-8b31-5dd95cf353f5,75ca1b09-c22a-435c-acfa-d83231485586,МД/Мини-Даркстор,10,16,2022-11-22 13:35:31.347859+03,2022-11-22 13:49:41.69869+03

In [95]:
df_02.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 230918 entries, 0 to 230917
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   assembly_id         230918 non-null  object
 1   box_id              230918 non-null  object
 2   store_format        230918 non-null  object
 3   sku                 230918 non-null  int64
 4   amount              230918 non-null  int64
 5   assembly_datetime   230918 non-null  object
 6   assembled_datetime  230918 non-null  object
dtypes: int64(2), object(5)
memory usage: 14.1+ MB

In [96]:
df_final = pd.concat([df_01, df_02], axis=0, join='outer', ignore_index=True)
df_final

,assembly_id,box_id,store_format,sku,amount,assembly_datetime,assembled_datetime
0,0000b6a4-445c-4f9e-b5d8-97b75332755f,5b4e7a6f-ec88-40a0-96ea-d9118c0fda34,МД/Супермаркет,10,11,2022-11-06 10:46:41.224447+03,2022-11-06 10:51:02.074923+03
1,000140d8-42e0-44f7-9f47-2460c52e241c,148da139-db62-4379-92af-2ed792723d45,МД/Магазин у дома,14,14,2022-11-12 19:06:37.021463+03,2022-11-12 19:15:34.670312+03
2,00019029-70e1-46e6-a454-b9c0c2158ee9,b1563abd-991d-46e0-8f96-affb6a2272f5,МД/Супермаркет,23,26,2022-11-01 13:49:13.915697+03,2022-11-01 14:08:32.053658+03
3,00023603-c39b-4db6-a4a0-356ff1613504,f830b34e-8cec-4207-a377-4154f60ebf63,МК/Мегаполис МК,12,12,2022-11-08 19:00:18.071688+03,2022-11-08 19:10:58.455788+03
4,00026957-a6d2-4fcb-aac8-716c368d84b4,018a67b7-7e3f-47d7-8ae9-1d9a81672c6c,МД/Магазин у дома,10,10,2022-11-09 11:28:10.573588+03,2022-11-09 11:36:46.808569+03
...,...,...,...,...,...,...,...
472998,ffff1987-da1a-462e-8161-a6a8928def60,7bae2653-ad9d-49ac-a2e4-0d912f075597,МД/Супермаркет,17,24,2022-11-26 15:02:59.043008+03,2022-11-26 15:52:23.129005+03
472999,ffff365d-e8a5-44a6-81b4-6a23edec17de,cae08e0b-17d1-4163-bf12-897c81790fd0,МД/Мини-Даркстор,48,59,2022-11-24 15:59:27.837839+03,2022-11-24 16:31:18.20236+03
473000,ffff77de-8838-4f6d-854b-1fb868f409d1,136dcb3b-f893-4d85-8f5b-1d780156cbe2,МД/Магазин у дома,4,4,2022-11-22 14:57:27.776063+03,2022-11-22 15:01:18.44135+03
473001,ffffb5a2-18dc-4b7c-aaea-614f2164603d,4978744f-5fea-4e50-98e2-dfea919924ed,МД/Магазин у дома,16,21,2022-11-16 10:59:02.245041+03,2022-11-16 11:17:57.616853+03
473002,ffffd931-0fc6-453b-8b31-5dd95cf353f5,75ca1b09-c22a-435c-acfa-d83231485586,МД/Мини-Даркстор,10,16,2022-11-22 13:35:31.347859+03,2022-11-22 13:49:41.69869+03

In [78]:
df_final.to_csv('out_0111-3011.csv', index=False)